server:
  port: 8090

logging:
  file: "f:/tmp/logs/imard/boot.log"


management:
  context-path: "/actuator"

spring:
  application:
    name: "@pom.artifactId@"
  boot:
    admin:
      url: http://127.0.0.1:8090
  profiles:
    active:
      - secure


---
management:
  security:
    enabled: false

security:
  basic:
    enabled: false

---

---
spring:
  profiles: secure
  boot:
    admin:
      username: "${security.user.name}"
      password: "${security.user.password}"
      client:
        metadata:
          user.name: "${security.user.name}"
          user.password:  "${security.user.password}"

security:
  user:
    name: alan
    password: alan

info:
  app:
    name: spring-boot-admin
    version: v1.0.0